<?php

namespace App\Http\Requests\Admin;

use App\Http\Requests\BaseRequest;

class LoginAdminRequest extends BaseRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'email'=>'required|email',
            'password'=>'required|min:6',
        ];
    }
    public function messages()
    {
        return [
            'email.email' => __('validation.correct_email'),
            'email.required'=>__('validation.email'),
            'password.required'=>__('validation.password'),
            'password.min'=>__('validation.min_password'),
        ]; // TODO: Change the autogenerated stub
    }
}
