/** أمثلة v2 بلا DOM؛ تصلح للاستيراد من اختبارات Node أو أدوات قبول المشروع. */
const field = (name, input, overrides = {}) => ({ name, column: name, input, type: input === 'switch' ? 'boolean' : ['boundary', 'map', 'multiform', 'image', 'file', 'upload_images', 'html', 'multi_select'].includes(input) ? 'json' : 'text', label_key: name, label_ar: name, label_en: name, language: 'neutral', ...overrides });
const base = (resource, model, titleAr, titleEn) => ({ schema_version: 2, resource: `demo_${resource}`, model: `Demo${model}`, controller: `Demo${model}Controller`, permission: `demo_${resource.replace(/s$/, '')}`, title_key: `demo_${resource}`, title_ar: titleAr, title_en: titleEn, create_model: true, timestamps: true, page_type: 'table', capabilities: { create: true, update: true, delete: true, delete_all: false, export: false, filters: true, show: false }, fields: [], edit_mode: 'same', edit_fields: [], columns: [], filters: [], actions: [], modals: [], sidebar: { mode: 'root', group: '', group_ar: '', group_en: '', icon: '', order: 0 }, notes: '' });

export const V2_EXAMPLES = {
    simple: { ...base('categories', 'Category', 'تصنيفات تجريبية', 'Demo categories'), fields: [field('name', 'text', { label_key: 'demo_category_name', label_ar: 'اسم التصنيف', label_en: 'Category name', language: 'both', validation: { required: true } }), { input: 'empty', width: '12' }, field('active', 'switch', { label_key: 'demo_category_active', label_ar: 'مفعّل', label_en: 'Active' })] },
    area: { ...base('areas', 'Area', 'المناطق', 'Areas'), fields: [field('city_id', 'single', { type: 'integer', label_ar: 'المدينة', label_en: 'City', select2: true, route: 'admin.cities.list', relation: { name: 'city', model: 'City', foreign_key: 'city_id', owner_key: 'id', value_name: 'name', key_name: 'id' }, storage: { strategy: 'belongsTo', relation: 'city' } }), field('boundary', 'boundary', { label_ar: 'الحدود', label_en: 'Boundary', storage: { strategy: 'custom' } })] },
    chain: { ...base('area_chains', 'AreaChain', 'سلسلة مناطق تجريبية', 'Demo area chain'), fields: [field('company_id', 'single', { type: 'integer', select2: true, route: 'admin.companies.list', relation: { name: 'company', model: 'Company', foreign_key: 'company_id', owner_key: 'id', value_name: 'name', key_name: 'id' } }), field('city_id', 'single', { type: 'integer', select2: true, route: 'admin.cities.list', parent_id: 'company_id', child_id: 'area_id', parent_key: 'company_id', child_key: 'city_id', relation: { name: 'city', model: 'City', foreign_key: 'city_id', owner_key: 'id', value_name: 'name', key_name: 'id' } }), field('area_id', 'single', { type: 'integer', select2: true, route: 'admin.areas.list', parent_id: 'city_id', parent_key: 'city_id', child_key: 'id', relation: { name: 'area', model: 'Area', foreign_key: 'area_id', owner_key: 'id', value_name: 'name', key_name: 'id' } })] },
    features: { ...base('features', 'Feature', 'الخصائص', 'Features'), fields: [field('image', 'image', { storage: { strategy: 'media', disk: 'public', directory: 'features' }, accepted_files: 'image/jpeg,image/png' }), field('children', 'multiform', { storage: { strategy: 'children', relation: 'children' }, min_rows: 0, max_rows: 8, inputs: [{ name: 'name_ar', label_ar: 'الاسم عربي', label_en: 'Arabic name', type: 'text' }, { name: 'name_en', label_ar: 'الاسم إنجليزي', label_en: 'English name', type: 'text' }] })] },
    email: { ...base('mail_types', 'MailType', 'أنواع البريد', 'Mail types'), fields: [field('admin_ids', 'multi_select', { select2: true, route: 'admin.admins.list', relation: { name: 'admins', model: 'Admin', foreign_key: 'admin_id', owner_key: 'id', value_name: 'name', key_name: 'id' }, storage: { strategy: 'pivot', relation: 'admins' } })] },
    product: { ...base('products', 'Product', 'منتجات تجريبية', 'Demo products'), fields: [field('tags_id', 'multi_select', { select2: true, route: 'admin.tags.list', relation: { name: 'tags', model: 'Tag', foreign_key: 'tag_id', owner_key: 'id', value_name: 'name', key_name: 'id' }, storage: { strategy: 'pivot', relation: 'tags' } }), field('related_ids', 'multi_select', { select2: true, route: 'admin.products.list', relation: { name: 'related', model: 'Product', foreign_key: 'product_id', owner_key: 'id', value_name: 'name', key_name: 'id' }, storage: { strategy: 'pivot', relation: 'related' } }), field('images', 'upload_images', { max_files: 14, max_file_size: 2, accepted_files: 'image/jpeg,image/png,image/webp', storage: { strategy: 'media', relation: 'images', disk: 'public', directory: 'products', deleted_key: 'deleted_images' } })] },
    actions: { ...base('orders', 'Order', 'الطلبات', 'Orders'), capabilities: { ...base('', '', '', '').capabilities, show: true }, fields: [field('status', 'single', { items: [{ value: 'ready', text_ar: 'جاهز', text_en: 'Ready', selected: true }, { value: 'draft', text_ar: 'مسودة', text_en: 'Draft', selected: false }] })], actions: [{ name_key: 'publish', name_ar: 'نشر', name_en: 'Publish', type: 'custom_modal', form_id: 'publish-order', icon: 'fa-check', permission: 'publish_order', operation: 'publish', if: [{ key: 'ready_to_publish', value: '1' }] }], modals: [{ id: 'publish-order', form_id: 'publish-order', title_key: 'publish_order', title_ar: 'نشر الطلب', title_en: 'Publish order', route: 'admin.orders.publish', method: 'POST', permission: 'publish_order', operation: 'publish', inputs: [] }] },
};

export const EXAMPLE_NAMES = Object.keys(V2_EXAMPLES);
