/** عرض آمن لمعاينة v2؛ كل نص خادم يدخل عبر textContent. */
import { languagePreviewFields } from './editor.js';
const el = (tag, text = '') => { const node = document.createElement(tag); node.textContent = text; return node; };
const copy = (ar, en) => document.documentElement.lang === 'en' ? en : ar;

export function renderPreview(result) {
    renderSummary(result); renderContractPreview(result); renderHandoffPlan(result); renderReasons(result.reasons || []); renderForms(result.form_preview); renderFiles(result.changes || result.files || {}); renderNextSteps(result.next_steps || []);
    document.querySelector('#preview-empty').hidden = true;
    document.querySelector('#file-count').textContent = result.mode === 'agent_required' ? copy('حزمة Agent مطلوبة', 'Agent package required') : `${(result.changes || Object.keys(result.files || {})).length} ${copy('تغييرًا', 'changes')}`;
}
export function renderSummary(result) { const container = document.querySelector('#preview-summary'); container.replaceChildren(); const card = el('section'); card.className = `summary-card ${result.mode === 'agent_required' ? 'agent' : 'direct'}`; const summary = result.summary ? (typeof result.summary === 'string' ? result.summary : Object.values(result.summary).filter(value => typeof value === 'string' || typeof value === 'number').join(' · ')) : (result.mode === 'agent_required' ? copy('هذا التعريف يحتاج تنفيذًا مخصصًا؛ لم تُنشأ صفحة عاملة.', 'This definition requires custom implementation; no working page was created.') : copy('العقد قابل للتوليد بعد مراجعة الملفات.', 'The contract can be generated after file review.')); card.append(el('strong', result.mode === 'agent_required' ? copy('جاهزة للتنفيذ بواسطة Agent', 'Ready for Agent implementation') : copy('توليد مباشر متاح', 'Direct generation available')), el('p', summary)); container.append(card); }
function label(item) { return document.documentElement.lang === 'en' ? item.label_en || item.name_en || item.title_en || item.label_ar || item.name || item.key : item.label_ar || item.name_ar || item.title_ar || item.label_en || item.name || item.key; }
function renderHandoffPlan(result) { if (result.mode !== 'agent_required') return; const handoff = result.handoff || {}; const files = handoff.file_plan || []; const functions = handoff.function_plan || []; if (!files.length && !functions.length) return; const container = document.querySelector('#preview-summary'); const section = el('section'); section.className = 'handoff-plan'; section.append(el('h3', copy('خطة Agent المقترحة', 'Proposed Agent plan')), el('p', copy('هذه عناصر مقترحة للتنفيذ؛ لم تُنشأ ملفات أو دوال عاملة.', 'These are proposed implementation items; no files or working methods were generated.'))); if (files.length) { section.append(el('h4', copy('ملفات مقترحة', 'Proposed files'))); const list = el('ul'); files.forEach(file => list.append(el('li', `${file.path || '—'} · ${file.operation || 'create'} · ${file.purpose || ''}`))); section.append(list); } if (functions.length) { section.append(el('h4', copy('دوال مقترحة', 'Proposed methods'))); const list = el('ul'); functions.forEach(method => list.append(el('li', `${method.method || '—'} · ${method.purpose || ''}`))); section.append(list); } container.append(section); }
function renderContractPreview(result) { const container = document.querySelector('#preview-summary'); const definition = result.definition || {}; const summary = result.summary || {}; const section = el('section'); section.className = 'contract-preview'; section.append(el('h3', copy('عقد الصفحة', 'Page contract'))); const facts = el('dl'); [['Route', summary.url || '' ], ['Controller', summary.controller || definition.controller || ''], ['Model', summary.model || definition.model || ''], [copy('الصلاحيات', 'Permissions'), (summary.permissions || []).join(', ') || '—']].forEach(([key, val]) => { const term = el('dt', key); const description = el('dd', val || '—'); facts.append(term, description); }); section.append(facts); const sidebar = summary.sidebar || definition.sidebar; if (sidebar) section.append(el('p', `${copy('القائمة', 'Sidebar')}: ${sidebar.mode || 'hidden'}${sidebar.group ? ` / ${sidebar.group}` : ''} · ${copy('الترتيب', 'order')} ${sidebar.order ?? 0}`)); const actions = definition.actions || []; const capabilities = summary.capabilities || definition.capabilities || {}; const standard = [['create', copy('إضافة', 'Create')], ['update', copy('تعديل', 'Edit')], ['delete', copy('حذف', 'Delete')], ['show', copy('عرض (الوجهة تحتاج استكمال)', 'Show (destination pending)')]].filter(([key]) => capabilities[key]).map(([, text]) => text); const actionLabels = actions.map(action => action.operation === 'show' ? `${label(action)} · ${copy('الرابط يحتاج استكمال', 'destination pending')}` : label(action)); section.append(el('p', `${copy('الأكشنات', 'Actions')}: ${[...standard, ...actionLabels].join(' · ') || '—'}`)); const columns = definition.columns || []; if (columns.length) { section.append(el('h4', copy('معاينة الجدول', 'Table preview'))); const table = document.createElement('table'); const head = document.createElement('thead'); const headRow = document.createElement('tr'); columns.forEach(column => headRow.append(el('th', label(column)))); head.append(headRow); const body = document.createElement('tbody'); const row = document.createElement('tr'); columns.forEach(column => row.append(el('td', `${column.type || 'text'} · ${column.key}`))); body.append(row); table.append(head, body); section.append(table); } container.append(section); }
export function renderReasons(reasons = []) { const container = document.querySelector('#preview-reasons'); container.replaceChildren(); if (!reasons.length) return; const box = el('section'); box.className = 'reasons'; box.append(el('h3', copy('لماذا يحتاج Agent؟', 'Why is an Agent required?'))); const list = el('ul'); reasons.forEach(reason => list.append(el('li', typeof reason === 'string' ? reason : reason.message || JSON.stringify(reason)))); box.append(list); container.append(box); }
function semanticControl(field) { const wrap = el('label'); wrap.className = 'mock-control'; const title = document.documentElement.lang === 'en' ? field.label_en || field.label_ar || field.label || field.name || field.input || 'field' : field.label_ar || field.label_en || field.label || field.name || field.input || 'field'; wrap.append(el('span', title)); const input = field.input || field.type || 'text'; let control; if (input === 'textarea' || input === 'html') { control = document.createElement('textarea'); control.rows = 2; control.placeholder = input === 'html' ? 'Rich-text editor contract' : title; } else if (input === 'single' || input === 'multi_select' || input === 'permissions') { control = document.createElement('select'); control.multiple = input === 'multi_select' || input === 'permissions'; const empty = document.createElement('option'); empty.textContent = input === 'single' ? copy('— اختر —', '— Select —') : 'Options'; control.append(empty); (field.items || []).forEach(item => { const option = document.createElement('option'); option.value = item.value; option.textContent = document.documentElement.lang === 'en' ? item.text_en || item.text_ar || item.value : item.text_ar || item.text_en || item.value; control.append(option); }); } else if (input === 'switch') { control = document.createElement('input'); control.type = 'checkbox'; } else if (input === 'image' || input === 'file' || input === 'upload_images') { control = document.createElement('div'); control.className = 'mock-dropzone'; control.textContent = input === 'upload_images' ? `Dropzone · ${field.max_files || '—'} files · ${field.max_file_size || '—'} MB` : 'File picker / stored-media preview'; } else if (input === 'image_preview') { control = document.createElement('div'); control.className = 'mock-image'; control.textContent = 'Stored media preview'; } else if (input === 'map') { control = document.createElement('div'); control.className = 'mock-map'; control.textContent = `Map → ${field.read_path || 'lat/lng fields'}`; } else if (input === 'boundary') { control = document.createElement('div'); control.className = 'mock-map'; control.textContent = 'Boundary polygon [[lat,lng], …]'; } else if (input === 'multiform') { control = document.createElement('div'); control.className = 'mock-children'; control.append(el('small', 'Children rows')); (field.inputs || []).flatMap(languagePreviewFields).forEach(child => control.append(semanticControl(child))); } else if (input === 'empty') { control = document.createElement('hr'); } else { control = document.createElement('input'); control.type = field.html_type || (input === 'hidden' ? 'hidden' : 'text'); control.placeholder = title; }
    if (control instanceof HTMLInputElement || control instanceof HTMLSelectElement || control instanceof HTMLTextAreaElement) { control.disabled = true; if (field.read_only) control.readOnly = true; }
    wrap.append(control, el('small', `${input}${field.read_only ? ' · read only' : ''}`)); return wrap; }
export function renderForms(forms = {}) { const container = document.querySelector('#preview-forms'); container.replaceChildren(); if (!forms || (!forms.create && !forms.edit)) return; const section = el('section'); section.className = 'form-preview'; section.append(el('h3', copy('معاينة النماذج', 'Form preview'))); [['create', copy('إضافة', 'Create')], ['edit', copy('تعديل', 'Edit')]].forEach(([key, title]) => { if (!forms[key]) return; const article = el('article'); article.append(el('h4', title)); const fields = Array.isArray(forms[key]) ? forms[key] : forms[key].fields || []; const controls = el('div'); controls.className = 'mock-controls'; fields.flatMap(languagePreviewFields).forEach(field => controls.append(semanticControl(field))); article.append(controls); section.append(article); }); container.append(section); }
export function renderFiles(changes) { const container = document.querySelector('#preview-files'); container.replaceChildren(); const entries = Array.isArray(changes) ? changes.map(change => [change.path, change]) : Object.entries(changes); entries.forEach(([path, change], index) => { const details = el('details'); details.className = 'file-item'; details.open = index === 0; const summary = el('summary', path); const operation = typeof change === 'object' ? change.operation || 'create' : 'create'; const badge = el('span', operation); badge.className = `operation ${operation}`; summary.append(badge); details.append(summary); const pre = el('pre', typeof change === 'object' ? (change.diff || change.after || change.before || '') : change); details.append(pre); container.append(details); }); }
export function renderNextSteps(steps = []) { const container = document.querySelector('#next-steps'); container.replaceChildren(); if (!steps.length) return; const section = el('section'); section.className = 'next-steps'; section.append(el('h3', copy('الخطوات التالية', 'Next steps'))); const list = el('ol'); steps.forEach(step => { const item = el('li'); const text = typeof step === 'string' ? step : step.text || JSON.stringify(step); item.append(el(text.startsWith('php ') ? 'code' : 'span', text)); list.append(item); }); section.append(list); container.append(section); }
export function showStatus(message, error = false) { const node = document.querySelector('#builder-status'); node.hidden = false; node.classList.toggle('error', error); node.textContent = message; }
